#!/bin/bash

# Update the ROUTER config parameters
sed -i -e "s/%%%ROUTER_SERVICE%%%/${ROUTER_SERVICE}/g" /etc/consul-templates/config.json.tmpl
sed -i -e "s/%%%ROUTER_REALM%%%/${ROUTER_REALM}/g" /etc/consul-templates/config.json.tmpl
sed -i -e "s/%%%ROUTER_PROTOCOL%%%/${ROUTER_PROTOCOL}/g" /etc/consul-templates/config.json.tmpl

cat /etc/consul-templates/config.json.tmpl

exec consul-template \
  -consul=$CONSUL_SERVER \
  -retry=1s \
  -template "/etc/consul-templates/config.json.tmpl:/app/src/config.json: cat /app/src/config.json; sv restart connect"
